apiVersion: v1
kind: Service
metadata:
  name: skillsync-service
  namespace: skillsync
spec:
  type: NodePort
  selector:
    app: skillsync
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007
